# Generated by Django 3.1.2 on 2020-10-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sleeve',
            name='sleeve',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
