# Generated by Django 3.1.2 on 2020-10-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201023_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='color',
            name='color',
        ),
        migrations.RemoveField(
            model_name='idealfor',
            name='idealFor',
        ),
        migrations.RemoveField(
            model_name='necktype',
            name='neckType',
        ),
        migrations.RemoveField(
            model_name='occasion',
            name='occasion',
        ),
        migrations.RemoveField(
            model_name='sleeve',
            name='sleeve',
        ),
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='title',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='color',
            name='slug',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='color',
            name='title',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idealfor',
            name='slug',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idealfor',
            name='title',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='necktype',
            name='slug',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='necktype',
            name='title',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sleeve',
            name='slug',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sleeve',
            name='title',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
