# Generated by Django 3.1.2 on 2020-10-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201023_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='color',
            name='slug',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='color',
            name='title',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='idealfor',
            name='slug',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='idealfor',
            name='title',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='necktype',
            name='slug',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='necktype',
            name='title',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='occasion',
            name='slug',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='occasion',
            name='title',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='sleeve',
            name='slug',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='sleeve',
            name='title',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
